export {
  prepareDeterministicPage,
  injectAnimationBlockingCSS,
  freezeTime,
  blockExternalRequests,
  isAllowedDomain,
  waitForLayoutStability,
  getLayoutBox,
  isLayoutStable,
  getDebugInfo,
  saveDebugInfo,
  DETERMINISTIC_DEFAULTS,
  type DeterministicOptions,
  type DeterministicDefaults,
  type DebugInfo,
  type BoundingBox,
} from '@ai-output-gate/playwright-deterministic-page';
