name: AI Gatekeeper

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps
      
      - name: Build app
        run: npm run build
      
      - name: Start app in background
        run: |
          npm run start &
          npx wait-on http://localhost:3000 --timeout 60000
      
      - name: Run AI Gatekeeper
        run: npx ai-gate run --baseURL http://localhost:3000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create review pack
        if: always()
        run: npx ai-gate review-pack
      
      - name: Upload evidence artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-gate-evidence
          path: .ai-gate/evidence/
          retention-days: 30
      
      - name: Upload review pack
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-gate-review-pack
          path: ai-gate-review-pack.zip
          retention-days: 30
      
      - name: Verify offline report
        if: always()
        run: npx tsx scripts/verify-offline-report.ts .ai-gate/evidence
